### ISSUE TITLE
Any roadmap?

### ISSUE THREAD

**Issue by Cydiater** [BobAnkh/THUBurrow#55]
Hey guys! I really appreciate your wonderful work here, and it makes me curious about your roadmap. Is there any release date for the new forum? And how can you keep it running under the pressure of government and school?

**Comment by BobAnkh** [comment]
Thank you for your appreciation. Actually, this is an experimental forum to try new tech stack, and also a project of Software Engineering course. Here is actually a simple current roadmap here in the course website: [roadmap](http://soft.cs.tsinghua.edu.cn/blog/?q=node/3936). We are trying to achieve a trade-off between anonymous forum and non-anonymous one.

But the roadmap is only for course use, so contains only a bunch of the features,  and I sure will extend more features after the course. I would keep on developing with new tech or new opinion. There is actually a plan to refactor the frontend in winter holidays.

There will be a alpha-test release next week at the latest.

I cannot ensure the site will be kept running forever if under severe pressure of gov or school. But as this is a great plantform not only for chatting(I originally would like to build a NGA for thu,lol.) but also for testing new tech stask(e.g. I want to implement webrtc for online game in winter holidays), I will try my best to keep it running.

Any suggestions are welcome! If you would like to help us(e.g. new idea, new opinion, management, etc.), please let me know.
